name: Deploy 

on:
  - workflow_dispatch

jobs:
  build:
    name: Build frontend using Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
      
      - name: Build app
        run: cd packages/client && bun run build
